name: azure-ml-demo
subscription_id: # Your Azure subscription ID
resource_group: azure-ml-demo-rg
workspace_name: azure-ml-demo-ws

compute_target:
  cpu_cluster:
    vm_size: STANDARD_DS3_v2
    min_nodes: 0
    max_nodes: 4
    idle_seconds_before_scaledown: 1800
  
  gpu_cluster:
    vm_size: STANDARD_NC6
    min_nodes: 0
    max_nodes: 2
    idle_seconds_before_scaledown: 1800

model_deployment:
  aks_target:
    name: aks-prod
    vm_size: STANDARD_DS3_v2
    cluster_purpose: FastProd
    initial_node_count: 3
    max_pods: 30

datastore:
  account_name: azuremldemo
  container_name: datasets
  
experiment_name: demo-classification
model_name: demo-classifier
